project:
  type: book

book:
  title: "2024 Ocean Conditions"
  author: "I. Schroeder"
  date: "12/07/2024"
  chapters:
    - index.qmd

      
    - part: Climate and Oceans
      chapters:
      - BasinScaleIndicators.qmd
      - JanFebNPH.qmd
      - SSTspatial.qmd
      - MarineHeatwaves.qmd
      - HabitatCompressionIndex.qmd
      - DepthTimeTemp.qmd
      - DepthTimeTempGlider.qmd
      - Upwelling.qmd

      
format:
  html:
    theme: cosmo
    
bibliography: esr-bibliography.bib
 

editor: visual

