project:
  type: book

book:
  title: "OC Environement Update for ESR"
  author: "Isaac Schroeder"
  date: "12/07/2024"
  chapters:
    - index.qmd

      
    - part: Climate and Oceans
      chapters:
      - BasinScaleIndicators.qmd
      - JanFebNPH.qmd
      - SSTspatial.qmd
      - MarineHeatwaves.qmd

      
format:
  html:
    theme: cosmo
    
bibliography: esr-bibliography.bib
 

editor: visual

