---
bibliography: /home/isaac/Work/IEA/2024/tech_document/tech_document.bib
format:
  html: 
    code-fold: true

---

# Habitat Compression Index


```{r}
ds_id <- 'cciea_OC_HCI'	   
ts_id_list = list('cciea_OC_HCI1', 'cciea_OC_HCI2', 'cciea_OC_HCI3', 'cciea_OC_HCI4')


# Source some local code
source("script_region.R")

```
**Description** The Habitat Compression Index (HCI) is the area of cool habitat along the coast, which is suitable for a diverse and productive portion of the CCE food web. HCI is estimated in four biogeographic provinces along the shelf within the CCE.

**Metafile name** `{r} fn_meta`
 
**Indicator Category** `{r} vec2[['Component_Section']]`
 
**Data Steward** `{r} vec2[['PI']]`

**Erddap Dataset ID** `{r} ds_id`

**CCIEA timeseries ID** `{r} ds_id_lbl`

**Region** `{r} rgn_lbl`

**References** @Santora2020, @Schroeder2022


**Public availability statement** Source data are publicly available.

**Data sources** Surface temperature data are the 2 m temperature levels of the University of California Santa Cruz 31-year historical reanalysis (<https://oceanmodeling.ucsc.edu/reanalccs31/>) and near-real-time (NRT; <https://oceanmodeling.ucsc.edu/ccsnrt/>) data-assimilative models.

**Data extraction** 

**Data analysis**
